### ISSUE TITLE
Can the top bar recolour to be consistent with a maximised title bar?

### ISSUE THREAD

**Issue by LumosX** [petar-v/gradienttopbar#10]
Hi! This extension is absolutely awesome, and I don't see myself using Gnome without it. The new experimental feature that removes the fade when a window is maximised is the dog's bollocks, but I noticed that when a window is maximised, the top bar reverts to a solid black. 

Would it be possible to have the top bar change colours to match the colour of the maximised window's title bar? Just an idea, I guess!

Thanks again for maintaining this project! It would have been a terrible loss to just let it die.

**Comment by petar-v** [comment]
Okay....

**Comment by petar-v** [comment]
This will be a bit tricky. It seems the gnome shell does not support proper gradient CSS: https://stackoverflow.com/questions/48241960/how-to-correctly-use-the-linear-gradient-while-styling-gnome-shell

Also, I couldn't find a way to dynamically add colours without interfering with other extensions. It is possible, however, to create a custom stylesheet, save it to a file and load/unload that.

**Comment by petar-v** [comment]
Please view https://github.com/petar-v/gradienttopbar/pull/11

**Comment by petar-v** [comment]
Now released. Closing this as complete. Thank you! :)
