### ISSUE TITLE
New update cannot view settings.

### ISSUE THREAD

**Issue by Ticklezz** [petar-v/gradienttopbar#12]
The settings of extension gradienttopbar@pshow.org had an error:
```
TypeError: Gtk.ColorDialog is undefined
```

Stack trace:
```
createColorChooserRow@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/settings/appearancePage.js:42:23
_init@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/settings/appearancePage.js:117:57
Appearance@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/settings/appearancePage.js:67:3
fillPreferencesWindow@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/prefs.js:26:26
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by petar-v** [comment]
Hi @Ticklezz! Thank you so much for reporting that! Do you mind letting me know what distro are you running this onto, please? It seems like you need gtk4 installed from a first glance at the issue...

**Comment by petar-v** [comment]
@Ticklezz , I think I have created a fix for this issue. Can you please download and test with the ["Test file" from this PR](https://github.com/petar-v/gradienttopbar/pull/13)? Thank you so much!

**Comment by petar-v** [comment]
Btw, an attempted fix for this has been shipped so you can just update from the official channels. I'll leave this issue open so I would appreciate if you can post an update if it works for you, @Ticklezz. Thank you! :)

**Comment by Ticklezz** [comment]
![Screenshot from 2023-06-02 00-25-33](https://github.com/petar-v/gradienttopbar/assets/113319295/b3425a58-c43f-4d1a-9973-3e3666297f62)
 New update still same issue.

**Comment by Ticklezz** [comment]
The settings of extension gradienttopbar@pshow.org had an error:
```
TypeError: Gtk.ColorDialog is undefined
```

Stack trace:
```
createColorDialogBtn@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/settings/components/colorDialog.js:7:23
createColorDialog@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/settings/components/colorDialog.js:37:38
createColorChooserRow@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/settings/appearancePage.js:43:39
_init@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/settings/appearancePage.js:106:57
Appearance@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/settings/appearancePage.js:56:3
fillPreferencesWindow@/home/bricktop/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org/prefs.js:26:26
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by petar-v** [comment]
Thank you so much for updating me on the issue, @Ticklezz ! Do you mind please sharing some more info on your distro? Which one is it and what version is it? Also, what is the version of Gnome you are running? 
Thank you!

**Comment by petar-v** [comment]
Actually, I was being a bit brain-dead when writing this. This [PR should fix it](https://github.com/petar-v/gradienttopbar/pull/14) :crossed_fingers:

**Comment by Ticklezz** [comment]
> Thank you so much for updating me on the issue, @Ticklezz ! Do you mind please sharing some more info on your distro? Which one is it and what version is it? Also, what is the version of Gnome you are running? Thank you!

I am on debian testing gnome 43.4.  This current fix worked and I can see the new settings introduced.

**Comment by Ticklezz** [comment]
I thank you for your great extension and all your efforts. I consider this closed and well done.

**Comment by petar-v** [comment]
:tada: Thank you so much! Appreciate it!

Apologies for the bug and thanks so much for helping with this issue, @Ticklezz ! :raised_hands:
