### ISSUE TITLE
Enhancement Suggestion : Tweaking Colored Icons on Systray

### ISSUE THREAD

**Issue by Anifyuli** [petar-v/gradienttopbar#4]
Hello, Mister.
I have a small suggestion for your extension. I like your extension and it run smoothly in Pop! OS 22.04.
I get a small "not good" contrast in colored icon and app icon in systray. I use Discord and Telegram Desktop for example.
![image](https://user-images.githubusercontent.com/73734843/235345762-0e521398-a8a1-4363-92cb-ce77615b8a08.png)

I wish it can enhance to better appearance with your GNOME Extension. Good luck. Take care your health, Mister.

**Comment by petar-v** [comment]
Hello! Thanks for your suggestion! 

The icons in the tray are something that is out of the scope of this project. I also wonder if it is possible to overwrite those with an extension. 

In the future, if time permits, I will add settings to change the gradient settings like the colour, transition, etc. For now, it is just a simple black gradient. As long as there is a user base for this, I am happy to add features and accept contributions. :) 

Take care as well and good luck! :)

**Comment by petar-v** [comment]
Closing the issue - out of scope.

**Comment by petar-v** [comment]
@Anifyuli Hi! I just discovered that you can change the icons via this extension: https://github.com/ubuntu/gnome-shell-extension-appindicator

Please look in the settings to discover this menu:
![image](https://user-images.githubusercontent.com/3801306/236928566-5fc519cc-1d09-4818-9c22-afc138dd8285.png)
