### ISSUE TITLE
Error: "global.get_workspace_manager is not a function"

### ISSUE THREAD

**Issue by slottwo** [petar-v/gradienttopbar#6]
Today this add-on simply stopped working, until yesterday it was normal, I had been using it for at least a week, I already restarted gnome, the session, the PC, reinstalled the add-on.

Error image:

![image](https://user-images.githubusercontent.com/41028091/235895963-8721e9c6-2bb9-48ef-bc69-bad6a1786540.png)

Other Extensions installed:

![image](https://user-images.githubusercontent.com/41028091/235895922-49860179-f8e3-4c9f-9386-11c6a89a091d.png)

System info:
![image](https://user-images.githubusercontent.com/41028091/235895007-bf502f60-c55c-4dc6-a53c-70d138a55b8a.png)

**Comment by snex** [comment]
Same here - Ubuntu 22.04.

**Comment by petar-v** [comment]
Thanks for reporting that! I have only tested the new changes on Gnome 44. I will revert to the older versions fo the extension for the older versions of gnome.

**Comment by petar-v** [comment]
I have updated the extension in extensions.gnome.org, please try reinstalling. For versions of GNOME below 43, please use this release: https://github.com/petar-v/gradienttopbar/releases/tag/44-0. 

Please let me know if this helps!

**Comment by snex** [comment]
I was able to make it work by manually selecting my gnome-shell version, downloading the zip file, then extracting it into ~/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org

Is there any way to get it to work via the https://extensions.gnome.org/local/ website? I don't understand why gnome insists on making these backwards-incompatible changes every time it releases a minor version.

**Comment by petar-v** [comment]
> I was able to make it work by manually selecting my gnome-shell version, downloading the zip file, then extracting it into ~/.local/share/gnome-shell/extensions/[gradienttopbar@pshow.org](mailto:gradienttopbar@pshow.org)


Yes, this is how you'd do it. 

> Is there any way to get it to work via the https://extensions.gnome.org/local/ website? I don't understand why gnome insists on making these backwards-incompatible changes every time it releases a minor version.

I have pushed an updated version to extensions.gnome.org just now. It is pending review. 

Tell me about the breaking changes... this is my first gnome shell extension so I am not really experienced in making those. But from what I can see in the APIs, there are a lot of breaking changes and some of the APIs don't really make sense to me. However, I'm sure there's a reason for those decisions. 

Anyways, for anything below GNOME 43, please use the old version of the extension. I've made the new changes be available only on the GNOME versions I can test on. Those are 43 and 44 for now. If find time and it's feasible, I'll try to backport features to older versions as well. 

I plan on extending the extension to have the gradient and effects configurable to some extent gradually over time so any help with testing or contributions are very much welcome! :)

**Comment by petar-v** [comment]
Thank you so much, @snex ! I will take you up on that offer. 

Meanwhile, please feel free to use my repo as a template to start your own extension. A good place to start is this website: https://gjs.guide/extensions/. Also, there are docs over here about all the APIs and versions https://gjs-docs.gnome.org/. On that first website, there is a tutorial on how to create a super simple extension with a simple settings page. Please feel free to reach out if you need any help developing that! :)

**Comment by snex** [comment]
Thanks for the info but I already made what I needed as a Zabbix pluigin.

**Comment by petar-v** [comment]
Hi, new versions of the extensions have now hit the EGO website. Please try updating or reinstalling the extension. I am closing this issue but if problems persist, please feel free to reopen. :)

**Comment by slottwo** [comment]
> Hi, new versions of the extensions have now hit the EGO website. Please try updating or reinstalling the extension. I am closing this issue but if problems persist, please feel free to reopen. :)

by EGO do you mean <https://extensions.gnome.org/>?
