### ISSUE TITLE
New update causing this. 

### ISSUE THREAD

**Issue by Ticklezz** [petar-v/gradienttopbar#7]
With new update when a window is maximized it does this when you switch to another open window.

![Screenshot from 2023-05-03 16-24-21](https://user-images.githubusercontent.com/113319295/236053249-19361b0d-35aa-4345-b10b-a5aa0449de9d.png)

**Comment by Alter-RK** [comment]
On the contrary, it becomes NOT transparent for me. So I confirm the problem

**Comment by petar-v** [comment]
Thank you for reporting this! I think have fixed the issue in this PR: https://github.com/petar-v/gradienttopbar/pull/8

Some feedback and testing will be much appreciated! :)

**Comment by petar-v** [comment]
This was an intended feature requested over here: https://github.com/petar-v/gradienttopbar/issues/2 

However, I do realize that not everyone wants to use it, so the aforementioned PR adds a button in the "Settings" menu of the extension to disable that feature.

**Comment by petar-v** [comment]
Upon further investigation, I think there might be interference with the extension Desktop Icons NG. This is related to the following issue reported here: https://github.com/pop-os/shell/issues/1075.

What OS and GNOME shell versions are you using?

**Comment by Alter-RK** [comment]
Understood, this is not a bug but a feature :) Yes, I would like to be able to turn it off. I am using GNOME 43.4 

Thanks for your work!

**Comment by Ticklezz** [comment]
> Upon further investigation, I think there might be interference with the extension Desktop Icons NG. This is related to the following issue reported here: [pop-os/shell#1075](https://github.com/pop-os/shell/issues/1075).
> 
> What OS and GNOME shell versions are you using? Also, what extensions do you have currently installed?

Debian 12 testing Gnome 43.4.

**Comment by petar-v** [comment]
Hi folks, a new release just went up. You can now enable/disable the "opaque on maximized" feature by going to the extension settings and toggling the switch. It should be off by default.

If this has solved the problems, please feel free to close the issue. Otherwise, please let me know if there are any bugs.

**Comment by Ticklezz** [comment]
> Hi folks, a new release just went up. You can now enable/disable the "opaque on maximized" feature by going to the extension settings and toggling the switch. It should be off by default.
> 
> If this has solved the problems, please feel free to close the issue. Otherwise, please let me know if there are any bugs.

Thank you so much!!
